deploy to ec2

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -3,27 +3,35 @@ name: Deploy Node Application
 on:
   push:
     branches:
-        - main
+      - main
 
 jobs:
-    build:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout Source
-              uses: actions/checkout@v4
-            - name: Login to docker hub
-              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
-            - name: Build Docker Image 
-              run: docker build -t vishnu463/fastmart-api .
-            - name: Publish Image to docker hub
-              run: docker push vishnu463/fastmart-api:latest
-    
-    deploy:
-        needs: build
-        runs-on: self-hosted 
-        steps:
-          - name: Pull image from docker hub
-            run: docker pull vishnu463/fastmart-api:latest
-          - name: Run Docker Container
-            run: docker run -d -p 4000:4000 --name fastmart-api-container -e MONGO_URL='${{secrets.MONGO_URL}}' vishnu463/fastmart-api
-            
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Source
+        uses: actions/checkout@v4
+      - name: Login to Docker Hub
+        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
+      - name: Build Docker Image
+        run: docker build -t vishnu463/fastmart-api .
+      - name: Publish Image to Docker Hub
+        run: docker push vishnu463/fastmart-api:latest
+  
+  deploy:
+    needs: build
+    runs-on: self-hosted
+    steps:
+      - name: Clean up old container (if any)
+        run: |
+          docker stop fastmart-api-container || true
+          docker rm fastmart-api-container || true
+          docker rmi vishnu463/fastmart-api:latest || true
+          rm -f /home/ubuntu/actions-runner-node/run.sh || true  # Clean up the conflicting file
+      
+      - name: Pull image from Docker Hub
+        run: docker pull vishnu463/fastmart-api:latest
+      
+      - name: Run Docker Container
+        run: docker run -d -p 4000:4000 --name fastmart-api-container -e MONGO_URL='${{secrets.MONGO_URL}}' vishnu463/fastmart-api
+
